export const meetupCategories = [
    { id: 1, name: "Tech" },
    { id: 2, name: "Business" },
    { id: 3, name: "Career & Networking" },
    { id: 4, name: "Outdoors & Adventure" },
    { id: 5, name: "Health & Wellness" },
    { id: 6, name: "Sports & Fitness" },
    { id: 7, name: "Food & Drink" },
    { id: 8, name: "Music" },
    { id: 9, name: "Film" },
    { id: 10, name: "Arts" },
    { id: 11, name: "Language & Culture" },
    { id: 12, name: "Book Clubs" },
    { id: 13, name: "Hobbies & Crafts" },
    { id: 14, name: "Games" },
    { id: 15, name: "Writing" },
    { id: 17, name: "Parenting" },
    { id: 18, name: "Fashion & Beauty" },
    { id: 19, name: "Pets & Animals" },
    { id: 20, name: "Home & Garden" },
    { id: 21, name: "Science & Tech" },
    { id: 22, name: "Education" },
    { id: 23, name: "Photography" },
    { id: 24, name: "Socializing" },
    { id: 25, name: "Volunteering" },
    { id: 27, name: "Environment" },
    { id: 28, name: "Travel & Places" },
    { id: 29, name: "Charity & Causes" },
    { id: 30, name: "Dance" },
  ];